### ISSUE TITLE
Is libuargp on par with the latest upstream version?

### ISSUE THREAD

**Issue by firasuke** [xhebox/libuargp#1]
Is your version of libuargp on par with the latest upstream version located over at:
https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/tree/libuargp

Thanks for your time and effort.

**Comment by xhebox** [comment]
No, I think. I will check and update.

**Comment by firasuke** [comment]
Thanks!

**Comment by xhebox** [comment]
It is force pushed. And the master should be the latest version. Close the issue if you are OK with it. :)

**Comment by firasuke** [comment]
Thank you for your hard work, looks good so far.

Closing.
